#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# m4 constant/polyMesh/blockMeshDict.m4 > constant/polyMesh/blockMeshDict

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm log.*
rm -r processor*

runApplication blockMesh
runApplication topoSet
runApplication createPatch -overwrite
runApplication setFields
runApplication decomposePar
runParallel RTMFoam 
runApplication reconstructPar
