* of6-rtm
** About the project
  This software is designed for simulations of mold filling and curing in resin transfer molding, a manufacturing process for continuous-fiber reinforced composites. It is based on [[https://github.com/OpenFOAM/OpenFOAM-6.git][OpenFOAM-6]], a free, open source computational fluid dynamics (CFD) software package released by the OpenFOAM Foundation. Relevant extensions presented in of6-rtm consist in heterogeneous and porosity dependent permeability, resin cure and cure dependent transport modelling.

  This software originates from KIT's Institute of Vehicle Systems Technology (FAST), Division Lightweight Engineering (Prof. Kärger).

** Getting started
  For instructions on how to set up the project locally, the user is referred to the [[https://openfoam.org/download/source][OpenFOAM installation instructions]].
  For the usage of the RTM extensions please have a look at the [[https://github.com/FAST-LB/of6-rtm/tree/main/tutorials/OF-RTM][RTM tutorials]]:
 1. Brinkman - permeability model verification case with the Brinkman equation for a channel with different permeabilities. See e.g. [[https://www.sciencedirect.com/science/article/pii/S0264127517306196][Syerko, 2017]]. 
 2. Bruschke - RTM verification  case after [[https://onlinelibrary.wiley.com/doi/abs/10.1002/pc.750110613][Bruschke, 1990]] for a plate with for quadrants with different fiber orientations.
 3. IRTM_test and CRTM_test - Simple 2D RTM case of a rectangular plate filled with a linear injection and a constant flow rate. Plate should be filled until 50% in IRTM_test and then Compression starts (tutorial CRTM_test). CRTM_test uses result of IRTM_test as start. After both tutorials you can run `gnuplot pressures.gnu` in the main tutorials folder. The file "pressures.pdf" is generated and should give the same result like the analytic solution plotted. 
 4. L-Section - L-shaped geometry with linear injection, **cure kinetics and cure viscosity**.
 
** Usage
  Description and examples from RTM tutorials. See also the [[https://openfoam.org/resources][OpenFOAM documentation]] and the [[https://cpp.openfoam.org/v6/][source documentation]].

** Contributing
When contributing to this repository, please first discuss the change you wish to make via issue,
email, or any other method with the owners of this repository before making a change.

Please note we have a code of conduct, please follow it in all your interactions with the project.

*** Pull Request Process

1. Ensure any install or build dependencies are removed before the end of the layer when doing a
   build.
2. Update the README.md with details of changes to the interface.
3. Increase the version numbers in any examples files and the README.md to the new version that this
   Pull Request would represent. The versioning scheme we use is [SemVer](http://semver.org/).
4. You may merge the Pull Request in once you have the sign-off of one other developer.

 You might have a look at the [[https://openfoam.org/dev/coding-style-guide][OpenFOAM C++ Style Guide]].
*** Code of Conduct

Please refer to our [[Code of Conduct][https://github.com/FAST-LB/of6-rtm/blob/main/CODE_OF_CONDUCT.md]].
 
** License
  of6-rtm is free software: you can redistribute it and/or modify it under the
  terms of the GNU General Public License as published by the Free Software
  Foundation, either version 3 of the License, or (at your option) any later
  version.  License terms under which you can copy the files can be found [[./COPYING][in our repo]] or at the
  [[https://www.gnu.org/licenses/][GNU license page]].

** Citing of6-rtm
  You need to cite of6-rtm when using it. Click [[./CITATION.cff][here]] to see how to cite of6-rtm.
A. Bernath, J. Seuffert, S. Dietrich, N. Poppe, D. Magagnato, F. Wittemann, F. Henning, L. Kärger. (2024) of6-rtm – An OpenFOAM-6 extension with curing models and anisotropic permeability for usage in LCM simulations. Karlsruhe Institute of Technology (KIT). available at: https://github.com/FAST-LB/of6-rtm DOI:

** Contributions Under Repository License
  Whenever you add Content to this repository, you license that Content under the terms defined in the license in the repository, and you agree that you have the right to license that Content under those terms. If you have a separate agreement to license that Content under different terms, such as a contributor license agreement, that agreement will supersede.
  Isn't this just how it works already? Yep. This is widely accepted as the norm in the open-source community; it's commonly referred to by the shorthand "inbound=outbound". We're just making it explicit.

** Contact
  FAST LB
  lt-github@fast.kit.edu
  Project Link: [[https://github.com/FAST-LB/of6-rtm]]

** Acknowledgements
- TC² - Technologycluster Composite, „RTM CAE/CAx - Development of a continuous CAE/CAx chain for the RTM process against the background of the production of high-performance fiber composites“  2011-2013
- SMILE - "System-integrative multi-material lightweight construction for electromobility" 2014-2017 BMBF (03X3041Q)
- SPP 1712 - "Basic investigations of intrinsically manufactured FRP/metal composites - from embedded insert to load-bearing hybrid structure" 2017-2020 German research foundation DFG (project HE 6154/3-2)
- Vector Foundation YIG Green Mobility "Weight-optimized vehicle structures through customized high-performance fiber composites" 2015-2020
- FSI Sandwich - “Modelling of the fluid-structure interaction in mold filling processes for an intrinsic manufacturing of fiber-reinforced composite sandwich components” 2021-2025 German research foundation DFG (project KA 4224/9-1 and HE 6154/8-1)
-	MerVa - "Method and process development for the infiltration of highly resilient topology-optimized fiber-polymer composite components with variable-axial fiber architecture" German research foundation DFG (project KA 4224/4-1)

*** Built With
- [[https://github.com/OpenFOAM/ThirdParty-6][OpenFOAM-6 third-party library compilation scripts]]
