* of6-rtm
** About the project
  This software is designed for simulations of mold filling and curing in resin transfer molding, a manufacturing process for continuous-fiber reinforced composites. It is based on [[https://github.com/OpenFOAM/OpenFOAM-6.git][OpenFOAM-6]], a free, open source computational fluid dynamics (CFD) software package released by the OpenFOAM Foundation. Relevant extensions presented in of6-rtm consist in heterogeneous and porosity dependent permeability, resin cure and cure dependent transport modelling.

This software originates from KIT's Institute of Vehicle Systems Technology (FAST), Division Lightweight Engineering (Prof. Kärger).

** Getting started
  For instructions on how to set up the project locally, the user is referred to the [https://openfoam.org/download/source][[OpenFOAM installation instructions]].
 
** Usage
  Description and examples from RTM tutorials. See also the [[https://openfoam.org/resources][OpenFOAM documentation]] and the [[https://cpp.openfoam.org/v6/][source documentation]].

** Contributing
  Contributions are what make the open source community such an amazing place to learn, inspire, and create. Any contributions you make are greatly appreciated.
  If you have a suggestion that would make this better, please fork the repo and create a merge request. You can also simply open an issue with the tag "enhancement".
  Don't forget to give the project a star! Thanks again!
  1. Fork the Project
  2. Create your Feature Branch (git checkout -b feature/NewFeature)
  3. Commit your Changes (git commit -m 'Add some NewFeature')
  4. Add yourself to docs/Contributors.md
  5. Push to the Branch (git push origin feature/NewFeature)
  6. Open a Merge Request

** License
  Copyright 2017-2024 Karlsruhe Institut of Technology (KIT)
  
  of6-rtm is free software: you can redistribute it and/or modify it under the
  terms of the GNU General Public License as published by the Free Software
  Foundation, either version 3 of the License, or (at your option) any later
  version.  License terms under which you can copy the files can be found [[./COPYING][in our repo]] or at the
  [[https://www.gnu.org/licenses/][GNU license page]].

** Citing of6-rtm
  You need to cite of6-rtm when using it. Click [[./CITATION.cff][here]] to see how to cite of6-rtm.
  
** Contributing
  You might have a look at the [[https://openfoam.org/dev/coding-style-guide][OpenFOAM C++ Style Guide]].

** Contributions Under Repository License
  Whenever you add Content to this repository, you license that Content under the terms defined in the license in the repository, and you agree that you have the right to license that Content under those terms. If you have a separate agreement to license that Content under different terms, such as a contributor license agreement, that agreement will supersede.
  Isn't this just how it works already? Yep. This is widely accepted as the norm in the open-source community; it's commonly referred to by the shorthand "inbound=outbound". We're just making it explicit.

** Contact
  FAST LB
  lt-github@fast.kit.edu
  Project Link: [[https://github.com/FAST-LB/of6-rtm]]

** Acknowledgements
-	Vector YIG
-	DFG MerVa
-	…

*** Built with third-party?
